### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by ghost** [svoboda18/android_advanced_treble_script#1]
Svoboda18 Hello, compile "lineage 16 and mokee (mkp) arm64avN" using your script. When applying patches to the source code synchronously, the following prompt will appear: "find:'vendor/interfaces': no such file or directory", but there is a "interfaces" folder in the vnedor directory. There are no other errors in the following period. When the compilation progress reaches 90%, the following problems occur:
"[ 82% 90079/108662] Target Java: /home...o_intermediates/classes-full-debug.jar
FAILED: /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/classes-full-debug.jar 
/bin/bash -c "(rm -f /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/classes-full-debug.jar ) && (rm -rf /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/classes /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/anno ) && (mkdir -p /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/ ) && (mkdir -p /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/classes /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/anno ) && (/home/*/android_advanced_treble_script/out/soong/host/linux-x86/bin/zipsync -d /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/srcjars -l /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/srcjar-list -f \"*.java\"  /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/aapt.srcjar ) && (if [ -s /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/java-source-list -o -s /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/srcjar-list ] ; then /home/*/android_advanced_treble_script/out/soong/host/linux-x86/bin/soong_javac_wrapper  prebuilts/jdk/jdk9/linux-x86/bin/javac -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline -encoding UTF-8   -bootclasspath /home/*/android_advanced_treble_script/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes-header.jar:/home/*/android_advanced_treble_script/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes-header.jar:/home/*/android_advanced_treble_script/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-header.jar:/home/*/android_advanced_treble_script/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar:/home/*/android_advanced_treble_script/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes-header.jar:/home/*/android_advanced_treble_script/out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar    -d /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/classes -s /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/anno  -source 1.8 -target 1.8 -g:source,lines  \\@/home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/java-source-list \\@/home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/srcjar-list || ( rm -rf /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/classes ; exit 41 ) fi ) && (prebuilts/jdk/jdk9/linux-x86/bin/jar -cf /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/classes-full-debug.jar     @<(find /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/classes -type f | sort | build/soong/scripts/jar-args.sh /home/*/android_advanced_treble_script/out/target/common/obj/APPS/QtiAudio_intermediates/classes; echo \"-C /home/*/android_advanced_treble_script/out/empty .\") )"
vendor/hardware_overlay/Qualcomm/QtiAudio/src/vendor/qti/hardware/radio/am/V1_0/IQcRilAudioCallback.java:221: error: cannot find symbol
                mRemote.transact(256462420 /* setHALInstrumentation */, _hidl_request, _hidl_reply, android.os.IHwBinder.FLAG_ONEWAY);
                                                                                                                        ^
  symbol:   variable FLAG_ONEWAY
  location: interface IHwBinder
vendor/hardware_overlay/Qualcomm/QtiAudio/src/vendor/qti/hardware/radio/am/V1_0/IQcRilAudioCallback.java:277: error: cannot find symbol
                mRemote.transact(257120595 /* notifySyspropsChanged */, _hidl_request, _hidl_reply, android.os.IHwBinder.FLAG_ONEWAY);
                                                                                                                        ^
  symbol:   variable FLAG_ONEWAY
  location: interface IHwBinder
vendor/hardware_overlay/Qualcomm/QtiAudio/src/vendor/qti/qcril/am/V1_0/IQcRilAudioCallback.java:221: error: cannot find symbol
                mRemote.transact(256462420 /* setHALInstrumentation */, _hidl_request, _hidl_reply, android.os.IHwBinder.FLAG_ONEWAY);
                                                                                                                        ^
  symbol:   variable FLAG_ONEWAY
  location: interface IHwBinder
vendor/hardware_overlay/Qualcomm/QtiAudio/src/vendor/qti/qcril/am/V1_0/IQcRilAudioCallback.java:277: error: cannot find symbol
                mRemote.transact(257120595 /* notifySyspropsChanged */, _hidl_request, _hidl_reply, android.os.IHwBinder.FLAG_ONEWAY);
                                                                                                                        ^
  symbol:   variable FLAG_ONEWAY
  location: interface IHwBinder
vendor/hardware_overlay/Qualcomm/QtiAudio/src/vendor/qti/hardware/radio/am/V1_0/IQcRilAudio.java:102: error: cannot find symbol
                mRemote.transact(1 /* setCallback */, _hidl_request, _hidl_reply, android.os.IHwBinder.FLAG_ONEWAY);
                                                                                                      ^
  symbol:   variable FLAG_ONEWAY
  location: interface IHwBinder
vendor/hardware_overlay/Qualcomm/QtiAudio/src/vendor/qti/hardware/radio/am/V1_0/IQcRilAudio.java:118: error: cannot find symbol
                mRemote.transact(2 /* setError */, _hidl_request, _hidl_reply, android.os.IHwBinder.FLAG_ONEWAY);
                                                                                                   ^
  symbol:   variable FLAG_ONEWAY
  location: interface IHwBinder
vendor/hardware_overlay/Qualcomm/QtiAudio/src/vendor/qti/hardware/radio/am/V1_0/IQcRilAudio.java:213: error: cannot find symbol
                mRemote.transact(256462420 /* setHALInstrumentation */, _hidl_request, _hidl_reply, android.os.IHwBinder.FLAG_ONEWAY);
                                                                                                                        ^
  symbol:   variable FLAG_ONEWAY
  location: interface IHwBinder
vendor/hardware_overlay/Qualcomm/QtiAudio/src/vendor/qti/hardware/radio/am/V1_0/IQcRilAudio.java:269: error: cannot find symbol
                mRemote.transact(257120595 /* notifySyspropsChanged */, _hidl_request, _hidl_reply, android.os.IHwBinder.FLAG_ONEWAY);
                                                                                                                        ^
  symbol:   variable FLAG_ONEWAY
  location: interface IHwBinder
vendor/hardware_overlay/Qualcomm/QtiAudio/src/vendor/qti/qcril/am/V1_0/IQcRilAudio.java:102: error: cannot find symbol
                mRemote.transact(1 /* setCallback */, _hidl_request, _hidl_reply, android.os.IHwBinder.FLAG_ONEWAY);
                                                                                                      ^
  symbol:   variable FLAG_ONEWAY
  location: interface IHwBinder
vendor/hardware_overlay/Qualcomm/QtiAudio/src/vendor/qti/qcril/am/V1_0/IQcRilAudio.java:118: error: cannot find symbol
                mRemote.transact(2 /* setError */, _hidl_request, _hidl_reply, android.os.IHwBinder.FLAG_ONEWAY);
                                                                                                   ^
  symbol:   variable FLAG_ONEWAY
  location: interface IHwBinder
vendor/hardware_overlay/Qualcomm/QtiAudio/src/vendor/qti/qcril/am/V1_0/IQcRilAudio.java:213: error: cannot find symbol
                mRemote.transact(256462420 /* setHALInstrumentation */, _hidl_request, _hidl_reply, android.os.IHwBinder.FLAG_ONEWAY);
                                                                                                                        ^
  symbol:   variable FLAG_ONEWAY
  location: interface IHwBinder
vendor/hardware_overlay/Qualcomm/QtiAudio/src/vendor/qti/qcril/am/V1_0/IQcRilAudio.java:269: error: cannot find symbol
                mRemote.transact(257120595 /* notifySyspropsChanged */, _hidl_request, _hidl_reply, android.os.IHwBinder.FLAG_ONEWAY);
                                                                                                                        ^
  symbol:   variable FLAG_ONEWAY
  location: interface IHwBinder
12 errors
[ 82% 90082/108662] Proguard: /home/so...ler_intermediates/classes-proguard.jar
ProGuard, version 5.1
Reading system jar [/home/*/android_advanced_treble_script/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes-header.jar]
Reading system jar [/home/*/android_advanced_treble_script/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes-header.jar]
Reading system jar [/home/*/android_advanced_treble_script/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-header.jar]
Reading system jar [/home/*/android_advanced_treble_script/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar]
Reading system jar [/home/*/android_advanced_treble_script/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes-header.jar]
Reading system jar [/home/*/android_advanced_treble_script/out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar]
Reading program jar [/home/*/android_advanced_treble_script/out/target/common/obj/APPS/ProxyHandler_intermediates/classes.jar]
Preparing output jar [/home/*/android_advanced_treble_script/out/target/common/obj/APPS/ProxyHandler_intermediates/classes-proguard.jar]
  Copying resources from program jar [/home/*/android_advanced_treble_script/out/target/common/obj/APPS/ProxyHandler_intermediates/classes.jar]
[ 82% 90084/108662] target Turbine: settings-logtags
ninja: build stopped: subcommand failed.
21:57:57 ninja failed with: exit status 1
someone@2:~/android/l16gsi/android_advanced_treble_script$ 
"
In addition, in adv-build.sh, mokee90, mainbranch= "9.0" should be changed to "mkp", otherwise it can not be synchronized.
I would appreciate it if you could tell me how to repair it.

**Comment by svoboda18** [comment]
Hello

That error is related to the overlays, and it seems there is a wrong thing with branches, will take a investigate and fix it as soon as possible.

And, thanks for that mokee hint, I will change it.

**Comment by svoboda18** [comment]
Fixed since 23837ca.
