### ISSUE TITLE
Empty build folder e-0.2

### ISSUE THREAD

**Issue by oda-alexandre** [svoboda18/android_advanced_treble_script#2]
Hello I build the rom e-0.2 with the command bash android_advanced_treble_script / adv * .sh e-0.2 arm64-ab-vanilla-nosu-userdebug but I can not find the rom the folder e-0.2 is empty?

Here is my dockerfile file :
[Dockerfile.txt](https://github.com/svoboda18/android_advanced_treble_script/files/3388958/Dockerfile.txt)

**Comment by svoboda18** [comment]
I will soon fix this, thanks for reporting.

**Comment by svoboda18** [comment]
But , I don't understand "I don't find the ROM in folder".

NB: the script DOESN'T created output folder of the whole ROM repo. It have to be called from root of new folder.
