### ISSUE TITLE
Difficulties while removing a patch

### ISSUE THREAD

**Issue by lisandrocarmona** [svoboda18/android_advanced_treble_script#4]
Now, on v.1, I'm facing difficulties to remove a conflicting patch:
**b22048782b4 Move SysuiDarkThemeOverlay to /system**

The error message suggests we use
**git rm <path>
git commit**

However, doing that with the **<ROM source>/frameworks/base/packages/overlays** remove all the folder from compiling, leading to compilation errors.
I've tried to find where is the patch located, but I can't find a specific file.
If I try to edit the **<ROM source>/frameworks/base/.git/sequencer/todo** file and remove the instruction
pick b22048782b4 Move SysuiDarkThemeOverlay to /system
The file is autorestored when patching process starts again

Can anybody guide me (preferable step by step) how to remove this specific patch from the compilation using v.1 of the script?
Thanks.

More info

1. **grep -ril SysuiDarkThemeOverlay** command gives me the following information:

device/phh/treble/rw-system.sh
build/make/target/product/sdk_base.mk
build/make/target/product/generic_no_telephony.mk
frameworks/base/packages/overlays/SysuiDarkThemeOverlay/Android.mk
frameworks/base/.git/MERGE_MSG
frameworks/base/.git/index
frameworks/base/.git/sequencer/todo

2. **Patch** is this one (or **patches/platform_frameworks_base/0016-Move-SysuiDarkThemeOverlay-to-system.patch** file if we were using the old script version):

From b22048782b4d57016ca6bad2d2c56560b91ab3da Mon Sep 17 00:00:00 2001
From: Pierre-Hugues Husson <phh@phh.me>
Date: Sun, 19 Aug 2018 10:57:21 +0200
Subject: [PATCH 16/34] Move SysuiDarkThemeOverlay to /system

Change-Id: I31b3edc5d1abcc1163a13e63c909fee9d27ff432
---
 packages/overlays/SysuiDarkThemeOverlay/Android.mk | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/packages/overlays/SysuiDarkThemeOverlay/Android.mk b/packages/overlays/SysuiDarkThemeOverlay/Android.mk
index 7b277bcf035..89cfcf819c2 100644
--- a/packages/overlays/SysuiDarkThemeOverlay/Android.mk
+++ b/packages/overlays/SysuiDarkThemeOverlay/Android.mk
@@ -11,4 +11,5 @@ LOCAL_RESOURCE_DIR := $(LOCAL_PATH)/res
 LOCAL_PACKAGE_NAME := SysuiDarkThemeOverlay
 LOCAL_SDK_VERSION := current
 
-include $(BUILD_RRO_PACKAGE)
+LOCAL_IS_RUNTIME_RESOURCE_OVERLAY := true
+include $(BUILD_PACKAGE)
-- 
2.17.1

**Comment by svoboda18** [comment]
Hello, hope you are fine, thanks for using my script as first, and also for reporting that issue. 

Unfortunately, you can't skip a ptach, or remove it. You can just fix it conflit. 'git status' shows you in red text files that are not properly marged, after editing, you can run 'git add .' followed by 'git cherry-pick - - continue' that's your patch progress continue. 

Well yes, on your situation, you can fix that conflit by editing the make file and seeing where it does conflit. (with cherry-pick, conflicts part are shown with '<<< HEAD' on file where it does) 

You have to fix conflicts instead of skipping it, literally it is incorrect.

**Comment by lisandrocarmona** [comment]
Thank you. I've tested a lot of different ways to fix the patch and really can't understand what is wrong. Any manual movement generates a different compilation error. I cannot figure out how "with cherry-pick, conflicts part are shown with '<<< HEAD' on file where it does".

I'll return to this some days later as I'll travel aboard.
Thank you again.

**Comment by svoboda18** [comment]
take a look to https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/HandlingAPatch/ResolveMergeConflicts.html#resolve-the-conflicts, though there is no way to skip a commit/patch unless you revert/ignore it is changes.
